inherit_gem:
  armitage-rubocop:
    - lib/rubocop.general.yml
    - lib/rubocop.rspec.yml

AllCops:
  TargetRubyVersion: 2.6.3
  Include:
    - bin/console
    - lib/**/*.rb
    - spec/**/*.rb
    - Gemfile
    - Rakefile
    - thy.gemspec

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/MultipleComparison:
  Enabled: false
